import { defineConfig } from "@playwright/test";

import config from "./playwright.eve.config";

export default defineConfig({
  ...config,
  testMatch: [
    "eve-logical-chat.e2e.ts",
    "eve-chat-identity.e2e.ts",
    "eve-optimistic-create.e2e.ts",
    "eve-copy-live.e2e.ts",
    "eve-copy-regeneration-live.e2e.ts",
    "eve-copy-documents-live.e2e.ts",
    "eve-comparison-live.e2e.ts",
    "eve-idle-checkpoint-live.e2e.ts",
    "eve-deletion-retire.e2e.ts",
    "eve-delete-dialog.e2e.ts",
    "eve-delete-ui.e2e.ts",
    "eve-deletion-fence.e2e.ts",
    "eve-mcp.e2e.ts",
    "eve-mcp-oauth.e2e.ts",
    "eve-model-picker.e2e.ts",
    "eve-tool-selection.e2e.ts",
    "eve-followups-ui.e2e.ts",
    "eve-followups-live.e2e.ts",
    "eve-image.e2e.ts",
    "eve-research.e2e.ts",
    "eve-create-recovery.e2e.ts",
    "eve-rejected-send.e2e.ts",
    "eve-document-run.e2e.ts",
    "eve-document-tools.e2e.ts",
    "eve-document-auto-open.e2e.ts",
    "eve-response-cards.e2e.ts",
    "eve-comparison-ui.e2e.ts",
    "eve-live.e2e.ts",
    "eve-code-execution.e2e.ts",
    "eve-sandbox-lifecycle.e2e.ts",
    "eve-search.e2e.ts",
    "eve-tool-renderers.e2e.ts",
    "eve-forks.e2e.ts",
    "eve-editing.e2e.ts",
    "eve-metadata.e2e.ts",
    "eve-feedback.e2e.ts",
    "eve-project-routing.e2e.ts",
    "eve-project-ui.e2e.ts",
    "eve-project-move.e2e.ts",
    "eve-project-instructions.e2e.ts",
    "eve-history.e2e.ts",
    "eve-attachments.e2e.ts",
    "eve-sharing.e2e.ts",
    "eve-pdf.e2e.ts",
  ],
  timeout: 120_000,
});
