// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: cf3a51371782990d91a266f2786979756a3ac2f3c50b947007936994b646d734
export const codeExecutionEnvRequirement = {"allOf":[{"description":"Vercel OIDC or team/project/token credentials","options":[["VERCEL_OIDC_TOKEN"],["VERCEL_TEAM_ID","VERCEL_PROJECT_ID","VERCEL_TOKEN"]],"runtimeAuth":"vercel-oidc"}],"description":"VERCEL_OIDC_TOKEN or VERCEL_TEAM_ID + VERCEL_PROJECT_ID + VERCEL_TOKEN","options":[["VERCEL_OIDC_TOKEN"],["VERCEL_TEAM_ID","VERCEL_PROJECT_ID","VERCEL_TOKEN"]]};
