// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 088a03f0781def9b873461eca72785fffab485ad83b335a461d9e4da342e4769
export const imageGenerationEnvRequirement = {"description":"","options":[[]]};
