// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 4b4206740e6f264f4ad6dd8892f62c2ed57576fb45a5b06edf084320fb88140d
export const searchEnvRequirement = {"description":"TAVILY_API_KEY","options":[["TAVILY_API_KEY"]]};
