// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: edb9d36a622c98252faf85c81bb495717a9a7209e4f5d2156533cd00d1c5a39f
import type { ToolSet } from "ai";
import { customTools } from "./custom-tools";
import { generateImageTool as tool0 } from "./generate-image/tool";
import { generateVideoTool as tool1 } from "./generate-video/tool";
import { getWeather as tool2 } from "./get-weather/tool";
import { retrieveUrl as tool3 } from "./retrieve-url/tool";
import { webSearch as tool4 } from "./tavily-search/tool";
import { codeExecution as tool5 } from "./vercel-code-execution/tool";
import { wordCount as tool6 } from "./word-count/tool";

const installed = {
  codeExecution: tool5,
  generateImage: tool0,
  generateVideo: tool1,
  getWeather: tool2,
  retrieveUrl: tool3,
  webSearch: tool4,
  wordCount: tool6,
} satisfies ToolSet;
for (const key of Object.keys(customTools)) {
  if (Object.hasOwn(installed, key)) {
    throw new Error(`Duplicate tool registration: ${key}`);
  }
}
export const tools = { ...installed, ...customTools };
