// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: b1a230de6eb84a9eed86992745954915242b313dc8fa9568872938efc09b0943
import type { ToolRendererRegistry } from "@/lib/ai/tool-renderer-registry";
import { customUi } from "./custom-ui";
import { GenerateImageRenderer as renderer0 } from "./generate-image/renderer";
import { GenerateVideoRenderer as renderer1 } from "./generate-video/renderer";
import { GetWeatherRenderer as renderer2 } from "./get-weather/renderer";
import { RetrieveUrlRenderer as renderer3 } from "./retrieve-url/renderer";
import { WebSearchRenderer as renderer4 } from "./tavily-search/renderer";
import { CodeExecution as renderer5 } from "./vercel-code-execution/renderer";
import { WordCountRenderer as renderer6 } from "./word-count/renderer";

const installed = {
  "tool-codeExecution": renderer5,
  "tool-generateImage": renderer0,
  "tool-generateVideo": renderer1,
  "tool-getWeather": renderer2,
  "tool-retrieveUrl": renderer3,
  "tool-webSearch": renderer4,
  "tool-wordCount": renderer6,
};
for (const key of Object.keys(customUi)) {
  if (Object.hasOwn(installed, key)) {
    throw new Error(`Duplicate renderer registration: ${key}`);
  }
}
export const ui = { ...installed, ...customUi } satisfies ToolRendererRegistry;
