// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: f6521868e12fd49d6edf7b846b71ac26c2ed29b1432c4e4e72f2c4a782606bec
export const urlRetrievalEnvRequirement = {"description":"FIRECRAWL_API_KEY","options":[["FIRECRAWL_API_KEY"]]};
