import assert from "node:assert/strict";

import { describe, it } from "vitest";

import {
  getFileImageProps,
  isFileStorageKey,
  keyFromFileUrl,
} from "./file-url";

describe("keyFromFileUrl", () => {
  const key = "l_u0a2bkphKLFKsBI4q5Tue9.png";

  it("reads path keys independently of metadata", () => {
    const path = `/api/files/${key}`;
    const url = new URL(path, "https://chat.example");
    url.searchParams.set("dpl", "dpl_test");
    url.searchParams.set("other", "ignored");
    assert.equal(keyFromFileUrl(path), key);
    assert.equal(keyFromFileUrl(url.href), key);
  });

  it("rejects invalid paths and query-only keys", () => {
    for (const url of [
      "/api/files/../secret",
      "/api/files/%2e%2e%2fsecret",
      `/api/files/${key}/extra`,
      `/api/files-other/${key}`,
      "/api/files/../file",
      `/api/files/content?key=${key}`,
    ]) {
      assert.equal(keyFromFileUrl(url), null);
    }
  });
});

describe("isFileStorageKey", () => {
  it("recognizes only keys generated by the Files SDK integration", () => {
    assert.equal(isFileStorageKey("l_u0a2bkphKLFKsBI4q5Tue9.png"), true);
    assert.equal(isFileStorageKey("legacy-upload-name.png"), false);
    assert.equal(isFileStorageKey("folder/legacy-upload.png"), false);
  });
});

describe("getFileImageProps", () => {
  it("makes managed worktree files same-origin for Next Image", () => {
    assert.deepEqual(
      getFileImageProps(
        "http://localhost:3030/api/files/l_u0a2bkphKLFKsBI4q5Tue9.png"
      ),
      {
        src: "/api/files/l_u0a2bkphKLFKsBI4q5Tue9.png",
        unoptimized: true,
      }
    );
  });

  it("leaves external images unchanged", () => {
    const url = "https://example.com/image.png";
    assert.deepEqual(getFileImageProps(url), { src: url, unoptimized: false });
  });
});
