import { spawnSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

import { MakerDeb } from "@electron-forge/maker-deb";
import { MakerDMG } from "@electron-forge/maker-dmg";
import { MakerRpm } from "@electron-forge/maker-rpm";
import { MakerSquirrel } from "@electron-forge/maker-squirrel";
import { MakerZIP } from "@electron-forge/maker-zip";
import type { ForgeConfig } from "@electron-forge/shared-types";

type Branding = {
  appName: string;
  appPrefix: string;
  appUrl: string;
  orgName?: string;
  orgEmail?: string;
};

// oxlint-disable-next-line unicorn/prefer-module -- Electron Forge loads this configuration through its CommonJS TypeScript loader.
const appRoot = __dirname;
const brandingPath = path.join(appRoot, "branding.json");
let prebuildComplete = false;

const runBunScript = (script: string, env: NodeJS.ProcessEnv = {}): void => {
  const result = spawnSync("bun", ["run", script], {
    env: { ...process.env, ...env },
    stdio: "inherit",
  });

  if (result.status !== 0) {
    throw new Error(
      `bun run ${script} failed with exit code ${result.status ?? "unknown"}`
    );
  }
};

const ensurePrebuild = (): void => {
  if (prebuildComplete) {
    return;
  }

  runBunScript("prebuild");
  prebuildComplete = true;
};

const loadBranding = (): Branding => {
  ensurePrebuild();

  if (!existsSync(brandingPath)) {
    throw new Error(
      `Electron packaging requires ${brandingPath}, but it was not generated by prebuild. ` +
        `Run \`bun run prebuild\` in ${appRoot} and try again.`
    );
  }

  const branding = JSON.parse(
    readFileSync(brandingPath, "utf-8")
  ) as Partial<Branding>;

  if (!branding.appName || !branding.appPrefix || !branding.appUrl) {
    throw new Error(
      `Electron branding file ${brandingPath} is invalid. Expected appName, appPrefix, and appUrl.`
    );
  }

  return branding as Branding;
};

const createForgeConfig = (): ForgeConfig => {
  const branding = loadBranding();
  const { appName, appPrefix, orgName, orgEmail } = branding;

  return {
    hooks: {
      generateAssets: () => {
        ensurePrebuild();
      },
      prePackage: () => {
        runBunScript("build", { NODE_ENV: "production" });
      },
      preStart: () => {
        runBunScript("build", { NODE_ENV: "development" });
      },
    },
    makers: [
      new MakerZIP({}, ["darwin"]),
      new MakerDMG(
        {
          name: `${appName}-mac`,
        },
        ["darwin"]
      ),
      new MakerSquirrel(
        {
          authors: orgName ?? appName,
          description: `${appName} desktop application`,
          name: appPrefix,
          setupExe: `${appName}-windows.exe`,
        },
        ["win32"]
      ),
      new MakerDeb(
        {
          options: {
            bin: appPrefix,
            categories: ["Utility"],
            homepage: branding.appUrl,
            icon: "./build/icon.png",
            maintainer:
              orgName && orgEmail
                ? `${orgName} <${orgEmail}>`
                : (orgName ?? orgEmail ?? appName),
          },
        },
        ["linux"]
      ),
      new MakerRpm(
        {
          options: {
            bin: appPrefix,
            homepage: branding.appUrl,
            icon: "./build/icon.png",
            license: "Apache-2.0",
          },
        },
        ["linux"]
      ),
    ],
    packagerConfig: {
      appBundleId: `dev.${appPrefix}.app`,
      appCategoryType: "public.app-category.productivity",
      asar: true,
      executableName: appPrefix,
      icon: "./build/icon",
      ignore: [
        /^\/out(?:$|\/)/u,
        /^\/release(?:$|\/)/u,
        /^\/src(?:$|\/)/u,
        /^\/node_modules(?:$|\/)/u,
        /^\/scripts(?:$|\/)/u,
        /^\/README\.md$/u,
        /^\/tsconfig\.json$/u,
      ],
      name: appName,
      protocols: [
        {
          name: `${appName} Auth`,
          schemes: [appPrefix],
        },
      ],
    },
  };
};

const config = createForgeConfig();

export default config;
